### ISSUE TITLE
Mobile vs. Web & Stack Decision

### ISSUE THREAD

**Issue by rohanvarshney** [rohanvarshney/LostThenFound#1]
We must decide which tech stack we want to use with respect to mobile development or web development, as well as deciding which type of application we want to develop for.

Mobile - Android (Kotlin which is similar to Java), iOS (Swift & xCode)

Web - Angular or NodeJs/Express/Heroku

Web - Ruby on Rails (antiquated)

Web - Django (Python)

Web - Java + Spring

**Comment by dbehailu** [comment]
I forgot to mention in our meeting but another option we have for web is - 
Firebase (database, user authentication), React(Next.js if we want to scale quickly) for frontend, and node.js for the backend. All of them are updated frequently and have decent documentation.

**Comment by rohanvarshney** [comment]
Based on our meeting on Friday January 29, 2021, we have decided to proceed with the MERN stack based on various reasons detailed in our Meeting Minutes for the week.
