### ISSUE TITLE
format date lost and time lost before adding post to db

### ISSUE THREAD

**Issue by dbehailu** [rohanvarshney/LostThenFound#56]

**Comment by rohanvarshney** [comment]
Current function convertDateFormat(originalDate) in Lost.js and Found.js have some behavior that may be pertinent? Not sure what exact formatting needs to be, might have to use DateTime objects or the equivalent in JavaScript since that class I know exists in Java.

**Comment by dbehailu** [comment]
I noticed the date format function after making the issue, I’ll try using that and if not I’ll play around with js’ DateTime

**Comment by dbehailu** [comment]
You're a beast, I just looked at it and it's perfect lol. Gonna upload date using the value you return from that method.
