### ISSUE TITLE
military time converter in Popup

### ISSUE THREAD

**Issue by dbehailu** [rohanvarshney/LostThenFound#64]
edit time string before rendering Post component

**Comment by dbehailu** [comment]
implemented a solution in the dates branch, but filtering still points to the unconverted dates (e.g. 15:00). 

we can use the convertTime method I added to Lost.js and Found.js within the filtering methods to fix this

**Comment by rohanvarshney** [comment]
I believe this has been resolved based on a Meeting Minutes call we had.
